config/routes.rb
Rails.application.routes.draw do

  root 'hq#index'

  get '/search_by_barcode/:id' => "hq#search_by_barcode"

  post '/push_merge' => "hq#push_merge"

  get '/query_to_print' => "hq#query_to_print"

  get '/birth_certificate/:id' => "hq#birth_certificate"

  post 'hq/do_print_these'

  post 'users/update_password'

  get 'users/change_password'

  get 'users/my_account'

  get '/search_by_case/:id' => "hq#search_by_case"

  get '/do_reopen_case/:id' => "hq#do_reopen_case"

  get '/do_close_case/:id' => "hq#do_close_case"

  get '/do_void_case/:id' => "hq#do_void_case"

  get 'hq/re_open_case'

  get 'hq/close_cases'

  get 'hq/void_cases'

  get 'hq/view_cases'
  
  get 'view_cases' => 'hq#view_cases'

  get 'hq/view_closed_cases'

  get 'hq/view_requests'

  get 'hq/manage_duplicates'

  get 'hq/reports'

  get 'hq/print_certificates'

  get 'hq/list_voided_cases'

  get 'hq/manage_sites'

  get 'hq/index'
  
  get 'hq/validate_records'
  
  get 'hq/compare_demographics'

  get "/query_voided" => "children#query_voided"

  get "/query_requests" => "children#query_requests"

  get "/query_closed" => "children#query_closed"

  get "/query" => "children#query"

  get "/view" => "children#view"

  get "/search" => "children#search"

  get "/logout" => "logins#logout"

  get "/login" => "logins#login"

  get "/search_by_fullname/:id" => "children#search_by_fullname"

  get "/search_by_fullname" => "children#search_by_fullname"

  get "/set_context/:id" => "logins#set_context"

  get "/view_users" => "users#view"

  get "/query_users" => "users#query"

  get "/search_user" => "users#search"

  get "/search_by_username/:id" => "users#search_by_username"

  get "/search_by_username" => "users#search_by_username"

  get "/username_availability" => "users#username_availability"

  get "/block_user/:id" => "users#block_user"

  get "/unblock_user/:id" => "users#unblock_user"

  get "/block" => "users#block"

  get "/unblock" => "users#unblock"
  
  get "/case_validation" => "hq#compare_demographics"
  
  get "/validate_records" => "hq#validate_records"
  
  get "/void_child" => "hq#void_child"

  resources :children

  resources :users

  resource :login do
    collection do
      get :logout
    end
  end	

end

app/models/user.rb
require 'couchrest_model'

class User < CouchRest::Model::Base

  use_database "local"

  def username
    self['_id']
  end

  def username=(value)
    self['_id'] = value
  end

  property :first_name, String
  property :last_name, String
  property :password_hash, String
  property :email, String
  property :active, TrueClass, :default => true
  property :notify, TrueClass, :default => false
  property :role, String
  property :site_code, String
  property :creator, String
  property :created_at, String
  property :updated_at, String
  # property :password_hashed_already, TrueClass, :default => false
  property :plain_password, String
  property :un_or_block_reason, String
  property :_rev, String

  timestamps!

  cattr_accessor :current_user

  def has_role?(role_name)
    self.current_user.role == role_name ? true : false
  end

  design do
    view :by_active

    # active views
    view :active_users,
         :map => "function(doc){
            if (doc['type'] == 'User' && doc['active'] == true){
              emit(doc._id, {username: doc._id ,first_name: doc.first_name,
              last_name: doc.last_name, email: doc.email,role: doc.role,
              creator: doc.creator, notify: doc.notify, updated_at: doc.updated_at});
            }
          }"

  end

  design do
    view :by_username,
         :map => "function(doc) {
                  if ((doc['type'] == 'User')) {
                    emit(doc['_id'], 1);
                  }
                }"
  end

  before_save do |pass|
    self.password_hash = BCrypt::Password.create(self.plain_password) if not self.plain_password.blank?

    self.plain_password = nil

    self.creator = 'admin' if self.creator.blank?
  end

  def password_matches?(plain_password)
    not plain_password.nil? and self.password == plain_password
  end

  def password
    @password ||= BCrypt::Password.new(password_hash)
  rescue BCrypt::Errors::InvalidHash
    Rails.logger.error "The password_hash attribute of User[#{self.username}] does not contain a valid BCrypt Hash."
    return nil
  end

  def password=(new_password)
    @password = BCrypt::Password.create(new_password)
    self.password_hash = @password
  end

  def self.create(params)
    user = User.new()
    user.username = params[:user]['username']
    user.plain_password = params[:user]['password']
    user.first_name = params[:user]['first_name']
    user.last_name = params[:user]['last_name']
    user.role = params[:user]['role']
    user.site_code = Site.current_code
    user.email = params[:user]['email']
    user.save
    return user
  end

  def self.edit(params)
    if params[:edit_action] == 'password_only'
      cur_user = User.current
      cur_user.plain_password = params[:user]['password']
      cur_user.save
    elsif params[:edit_action] == 'edit'
      cur_user = Utils::UserUtil.get_active_user(params[:username])
      cur_user.first_name = params[:user]['first_name']
      cur_user.last_name = params[:user]['last_name']
      cur_user.role = params[:user]['role']
      cur_user.email = params[:user]['email']
      cur_user.save
    end

    true
  end

  def self.get_active_user(username)
    user_hash = User.active_users.keys [username]
    return if user_hash.blank?
    username = user_hash.rows.first['value']['username']
    User.find username
  end

  def confirm_password
    password_hash
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!--style>

    .record td {
        font-size: 18px;
        font-style: italic;
        color: #000;
    }

    .record td strong {
        font-size: 14px;
        font-style: normal;
        color: #3465a4;
    }

    fieldset {
        margin: 20px;
        border-radius: 5px;
        border: 1px solid #3465a4;
        padding: 20px;
    }

    legend {
        font-size: 18px;
        font-weight: normal;
        color: #3465a4;
    }

</style-->

<%= form_for(@user) do |f| %>

    <fieldset>
      <legend>
        User Details
      </legend>

      <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
              <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <table cellpadding="5" width="90%" style="margin: auto; margin-top: 0px;">
        <tr>
          <td colspan="2">
            &nbsp;
          </td>
          <td>
            <span id='notice' style="font-style: italic; font-size: 0.9em;"></span><br/>
          </td>
        </tr>
        <tr>
          <td align="right">
            <%= f.label :username %>
          </td>
          <td>
            :
          </td>
          <td>
            <% if request.path.match(/new/) %>

                <%= f.text_field :username, :class => "input_cell", :placeholder => "Username", :required => true, :textCase => "lower", :uniq_check => "/username_availability?search_str=" %>

            <%else %>

                <%= f.text_field :username, :class => "input_cell", :placeholder => "Username", :required => true, :textCase => "lower" %>

            <% end %>
          </td>
        </tr>
        <tr>
          <td align="right">
            <%= f.label :first_name %>
          </td>
          <td>
            :
          </td>
          <td>
            <%= f.text_field :first_name, :class => "input_cell", :placeholder => "First Name", :required => true %>
          </td>
        </tr>
        <tr>
          <td align="right">
            <%= f.label :last_name %>
          </td>
          <td>
            :
          </td>
          <td>
            <%= f.text_field :last_name, :class => "input_cell", :placeholder => "Last Name", :required => true %>
          </td>
        </tr>

        <% @roles = [['', ''], ['Standard', 'standard'], ['Administrator', 'admin']].uniq %>

        <tr>
          <td align="right">
            <%= f.label :role %>
          </td>
          <td>
            :
          </td>
          <td>
            <%= select_tag "user[role]", options_for_select(@roles, @user.role), :class => 'input_cell', :placeholder => "Select user role", :required => true, :style => "width: 81.4% !important;" %>
          </td>
        </tr>

        <% if request.path.match(/new/) %>

            <tr>
              <td align="right">
                <label for="user_plain_password">Password</label>
              </td>
              <td>
                :
              </td>
              <td>
                <%= f.password_field :plain_password, :class => "input_cell", :placeholder => "Password", :required => true, :textCase => "lower" %>
              </td>
            </tr>

            <tr>
              <td align="right">
                <%= f.label :confirm_password %>
              </td>
              <td>
                :
              </td>
              <td>
                <%= f.password_field :confirm_password, :class => "input_cell", :placeholder => "Confirm the password entered", :required => true, :textCase => "lower" %>
              </td>
            </tr>

        <% else %>

            <tr>
              <td colspan="3">
                <%= f.hidden_field :password_hash, :class => "input_cell", :placeholder => "Password", :required => true %>
                <%= f.hidden_field :confirm_password, :class => "input_cell", :placeholder => "Confirm the password entered", :required => true %>
              </td>
            </tr>

        <% end %>

        <tr>
          <td align="right">
            <%= f.label :email %>
          </td>
          <td>
            :
          </td>
          <td>
            <%= f.text_field :email, :class => "input_cell", :placeholder => "Email Address", :optional => true %>
          </td>
        </tr>
      </table>

      <div class="actions">
        <%= f.hidden_field :_rev %>
        <%= f.hidden_field :created_at %>
        <%= f.hidden_field :updated_at %>
        <%#= f.submit :id => "btnAction", :class => "buttons blue", :style => "position: absolute; right: 160px; bottom: 20px;", :onclick => "submitForm()"  %>
      </div>

    </fieldset>

<% end %>

<!--button id="btnAction" class="blue" style="position: absolute; right: 160px; bottom: 20px;" onclick="submitForm()">
  <%= request.path.match(/new/) ? "Save" : "Update" %> User
</button-->

<script>

    var timerHnd;

    var good = <%= request.path.match(/new/) ? false : true %>

            function submitForm() {
                if (validateForm() && good) {
                    document.getElementsByTagName('form')[0].submit();
                }
            }

    function validateForm() {
        username = document.getElementById('user_username');
        first_name = document.getElementById('user_first_name');
        last_name = document.getElementById('user_last_name');
        user_role = document.getElementById('user_role');
        password = document.getElementById('user_password_hash');
        password_confirm = document.getElementById('user_confirm_password');

        if (username.value == '') {
            alert("Please enter username ...");
            return false;
        } else if (first_name.value == '') {
            alert("Please enter user first name ...");
            return false;
        } else if (last_name.value == '') {
            alert("Please enter user last name ...");
            return false;
        } else if (password.value == '') {
            alert("Please password ...");
            return false;
        } else if (password.value.length < 6) {
            alert("Please password should be atleast six characters ....");
            return false;
        } else if (password.value != password_confirm.value) {
            alert("The two passwords you enter do not match ...");
            return false;
        } else if (user_role.value == '') {
            alert("Please select user role ...");
            return false;
        }

        return true;
    }

    var timeSpacing = 500;

    function checkUsername() {

        clearTimeout(timerHnd);

        username = document.getElementById('user_username').value;

        if (username == "Username" || username.trim().length == 0) {
            timerHnd = setTimeout("checkUsername()", timeSpacing);

            return;
        }

        if (window.XMLHttpRequest) {// code for IE7+, Firefox, Chrome, Opera, Safari
            xmlhttp = new XMLHttpRequest();
        } else {// code for IE6, IE5
            xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
        }
        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
                var results = xmlhttp.responseText;

                timerHnd = setTimeout("checkUsername()", timeSpacing);

                if (results == 'undefined' || results == '' || results == '"not validate"') {
                    return;
                } else {
                    if (results == 'available') {
                        good = true;

                        document.getElementById('notice').innerHTML = 'Username ' + results;
                        document.getElementById('notice').style.color = 'green';

                        if(document.getElementById('btnAction')) {
                            document.getElementById('btnAction').disabled = false;
                            document.getElementById('btnAction').className = "blue";
                        }
                    } else {
                        good = false;

                        document.getElementById('notice').innerHTML = 'Username ' + results + "!";
                        document.getElementById('notice').style.color = 'red';

                        if(document.getElementById('btnAction')) {
                            document.getElementById('btnAction').disabled = 'disabled';
                            document.getElementById('btnAction').className = "gray";
                        }
                    }
                }
            }
        }
        xmlhttp.open("GET", "/username_availability?search_str=" + username, true);
        xmlhttp.send();

    }

    <% if request.path.match(/new/) %>

    // timerHnd = setTimeout("checkUsername()", timeSpacing);

    <% else %>

    if (document.getElementById("user_username")) {

        document.getElementById("user_username").disabled = true;

    }

    <% end %>

    init();

</script>

app/views/users/block.html.erb
<style>

    .record td {
        font-size: 18px;
        font-style: italic;
        color: #000;
    }

    .record td strong {
        font-size: 14px;
        font-style: normal;
        color: #3465a4;
    }

    fieldset {
        margin: 20px;
        border-radius: 5px;
        border: 1px solid #3465a4;
        padding: 20px;
    }

    legend {
        font-size: 18px;
        font-weight: normal;
        color: #3465a4;
    }

</style>

<fieldset>

  <fieldset>
    <form autocomplete="off">
      <table cellpadding="5" width="90%" style="margin: auto; margin-top: 30px;">
        <tr>
          <td align="right">
            Search for Username
          </td>
          <td>
            :
          </td>
          <td>
            <input type="text" class="input_cell" id="username" name="username" value="" style="width: 97%;" onclick="checkPopUp()"/>
          </td>
        </tr>
        <tr>
          <td align="right">
            Username
          </td>
          <td>
            :
          </td>
          <td>
            <input type="text" class="input_cell" id="uname" name="uname" value="" style="width: 97%;" disabled/>
          </td>
        </tr>
        <tr>
          <td align="right">
            First Name
          </td>
          <td>
            :
          </td>
          <td>
            <input type="text" class="input_cell" id="fname" name="fname" value="" style="width: 97%;" disabled/>
          </td>
        </tr>
        <tr>
          <td align="right">
            Last Name
          </td>
          <td>
            :
          </td>
          <td>
            <input type="text" class="input_cell" id="lname" name="lname" value="" style="width: 97%;" disabled/>
          </td>
        </tr>
        <tr>
          <td align="right">
            Role
          </td>
          <td>
            :
          </td>
          <td>
            <input type="text" class="input_cell" id="role" name="role" value="" style="width: 97%;" disabled/>
          </td>
        </tr>
        <tr>
          <td align="right">
            Reason:
          </td>
          <td>
            :
          </td>
          <td>
            <input type="text" class="input_cell" id="reason" name="reason" value="" style="width: 97%;" />
          </td>
        </tr>
      </table>
    </form>

    <button id="btnAction" class="gray" style="position: absolute; right: 160px; bottom: 20px;">Block User</button>

  </fieldset>

  <fieldset></fieldset>

</fieldset>

<script>

    var users = [];

    var timerHnd;

    var active = false;

    function __$(id) {
        return document.getElementById(id);
    }

    function checkCtrl(obj) {
        var o = obj;
        var t = o.offsetTop;
        var l = o.offsetLeft + 1;
        var w = o.offsetWidth;
        var h = o.offsetHeight;

        while ((o ? (o.offsetParent != document.body) : false)) {
            o = o.offsetParent;
            t += (o ? o.offsetTop : 0);
            l += (o ? o.offsetLeft : 0);
        }
        return [w, h, t, l];
    }

    function checkPopUp() {

        if (__$("popup")) {

            clearTimeout(timerHnd);

            document.body.removeChild(__$("popup"));

        } else {

            ajaxTasks();

        }

    }

    function ajaxTasks() {

        clearTimeout(timerHnd);

        var name = __$("username").value.trim();

        var url = "/search_by_username/" + name;

        var httpRequest = new XMLHttpRequest();
        httpRequest.onreadystatechange = function () {
            handleTasks(httpRequest);
        };
        try {
            httpRequest.open('GET', url, true);
            httpRequest.send(null);
        } catch (e) {
        }
    }

    function handleTasks(aXMLHttpRequest) {
        if (!aXMLHttpRequest) return;

        if (aXMLHttpRequest.readyState == 4 && (aXMLHttpRequest.status == 200 ||
                aXMLHttpRequest.status == 304)) {

            var result = JSON.parse(aXMLHttpRequest.responseText);

            users = result;

            loadRows();

        }
    }

    function loadRows() {

        if (!__$("popup")) {

            var pos = checkCtrl(__$("username"));

            var popup = document.createElement("div");
            popup.style.position = "absolute";
            popup.style.width = (pos[0] - 3) + "px";
            popup.style.height = "200px";
            popup.style.border = "1px solid #3465a4";
            popup.style.backgroundColor = "rgba(255,255,255,0.9)";
            popup.style.overflow = "auto";
            popup.style.top = (pos[2] + pos[1] + 2) + "px";
            popup.style.left = pos[3] + "px";
            popup.id = "popup";

            document.body.appendChild(popup);

        }

        __$("popup").innerHTML = "";

        if (!active)
            clearFields();

        for (var i = 0; i < users.length; i++) {

            var row = document.createElement("div");
            row.style.margin = "5px";
            row.style.border = "1px solid #ccc";
            // row.style.height = "50px";
            row.style.cursor = "pointer";
            row.innerHTML = "&nbsp;";
            row.setAttribute("pos", i);
            row.setAttribute("tag", (i % 2 > 0 ? "odd" : "even"));
            row.style.verticalAlign = "middle";
            row.style.padding = "20px";

            row.innerHTML = users[i]["username"];

            row.style.backgroundColor = (i % 2 > 0 ? "#fff" : "#eee");

            row.onmouseover = function () {

                this.style.backgroundColor = "lightblue";

            }

            row.onmouseout = function () {

                if (this.getAttribute("tag") == "even") {

                    this.style.backgroundColor = "#eee";

                } else {

                    this.style.backgroundColor = "#fff";

                }


            }

            row.onclick = function () {

                active = true;

                clearTimeout(timerHnd);

                loadItem(this.getAttribute("pos"));

            }

            __$("popup").appendChild(row);

        }

        if (!active && __$("fname").value.trim().length == 0) {

            timerHnd = setTimeout("ajaxTasks()", 1000);

        }

    }

    function loadItem(pos) {

        clearTimeout(timerHnd);

        if (__$("username")) {

            __$("username").value = users[pos]["username"];

        }

        if (__$("uname")) {

            __$("uname").value = users[pos]["username"];

        }

        if (__$("fname")) {

            __$("fname").value = users[pos]["fname"];

        }

        if (__$("lname")) {

            __$("lname").value = users[pos]["lname"];

        }

        if (__$("role")) {

            __$("role").value = users[pos]["role"];

        }

        document.body.removeChild(__$("popup"));

        if (__$("btnAction")) {

            __$("btnAction").className = "blue";

            __$("btnAction").onclick = function () {

                if(confirm("Are you sure?")) {

                    if(__$("reason").value.trim().length == 0){

                        alert("Please enter reason for blocking!");

                        __$("reason").focus();

                    } else {

                        window.location = "/block_user/" + users[pos]["username"];

                    }

                }


            }

        }

        active = false;

    }

    function clearFields() {

        if (__$("uname")) {

            __$("uname").value = "";

        }

        if (__$("fname")) {

            __$("fname").value = "";

        }

        if (__$("lname")) {

            __$("lname").value = "";

        }

        if (__$("role")) {

            __$("role").value = "";

        }

        if (__$("btnAction")) {

            __$("btnAction").className = "gray";

            __$("btnAction").onclick = function () {
            };

        }

    }

</script>

app/views/users/change_password.html.erb
<div style="display: table; width: 100%; border-spacing: 20px; color: #3465a4; font-size: 32px; margin-top: 50px;">

  <div style="display: table-row;">

    <div style="display: table-cell; text-align: right; width: 45%;">

      Current Password

    </div>

    <div style="display: table-cell; text-align: center;">

      :

    </div>

    <div style="display: table-cell; width: 45%;">

      <input type="password" name="old_password" id="old_password" value="" class="input_cell"/>

    </div>

  </div>

  <div style="display: table-row;">

    <div style="display: table-cell; text-align: right; width: 45%;">

      &nbsp;

    </div>

    <div style="display: table-cell; text-align: center;">

      &nbsp;

    </div>

    <div style="display: table-cell; width: 45%;">

      &nbsp;

    </div>

  </div>

  <div style="display: table-row;">

    <div style="display: table-cell; text-align: right; width: 45%;">

      New Password

    </div>

    <div style="display: table-cell; text-align: center;">

      :

    </div>

    <div style="display: table-cell; width: 45%;">

      <input type="password" name="new_password" id="new_password" value="" class="input_cell"/>

    </div>

  </div>

  <div style="display: table-row;">

    <div style="display: table-cell; width: 45%;">

      &nbsp;

    </div>

    <div style="display: table-cell; text-align: center;">

      &nbsp;

    </div>

    <div style="display: table-cell; width: 45%;">

      &nbsp;

    </div>

  </div>

  <div style="display: table-row;">

    <div style="display: table-cell; text-align: right; width: 45%;">

      Confirm Password

    </div>

    <div style="display: table-cell; text-align: center;">

      :

    </div>

    <div style="display: table-cell; width: 45%;">

      <input type="password" name="confirm_password" id="confirm_password" value="" class="input_cell"/>

    </div>

  </div>

  <div style="display: table-row;">

    <div style="display: table-cell; text-align: right; width: 45%;">

      &nbsp;

    </div>

    <div style="display: table-cell; text-align: center;">

      &nbsp;

    </div>

    <div style="display: table-cell; width: 45%;">

      &nbsp;

    </div>

  </div>

  <div style="display: table-row;">

    <div style="display: table-cell; text-align: right; width: 45%;">

      <div style="border: 1px dotted #ccc; width: 82%; height: 220px; border-radius: 10px; float: right;">

        &nbsp;

      </div>

    </div>

    <div style="display: table-cell; text-align: center;">

      &nbsp;

    </div>

    <div style="display: table-cell; width: 45%;">

      <div style="border: 1px dotted #ccc; width: 82%; height: 220px; border-radius: 10px; float: left;">

        &nbsp;

      </div>

    </div>

  </div>

</div>

<button id="btnAction" class="blue" style="position: absolute; right: 160px; bottom: 20px;" onclick="changePassword();">Update
  Password
</button>

<script>

    function __$(id) {
        return document.getElementById(id);
    }

    function changePassword() {

        if (__$("new_password") && __$("confirm_password") && __$("old_password") && (
                __$("new_password").value.trim().length == 0 || __$("confirm_password").value.trim().length == 0 ||
                __$("old_password").value.trim().length == 0)) {

            alert("Please fill all fields!");

        } else if (__$("new_password") && __$("confirm_password") && __$("new_password").value.trim() !=
                __$("confirm_password").value.trim()) {

            alert("Password Mismatch!");

        } else {

            ajaxSave();

        }

    }

    function ajaxSave() {

        var url = "/users/update_password";

        var data = "old_password=" + __$("old_password").value.trim() + "&new_password=" + __$("new_password").value.trim();

        var httpRequest = new XMLHttpRequest();
        httpRequest.onreadystatechange = function () {
            handleSave(httpRequest);
        };
        try {
            httpRequest.open('POST', url, true);
            httpRequest.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            httpRequest.setRequestHeader("X-Requested-With", "XMLHttpRequest");
            httpRequest.send(data);

        } catch (e) {
        }
    }

    function handleSave(aXMLHttpRequest) {
        if (!aXMLHttpRequest) return;

        if (aXMLHttpRequest.readyState == 4 && (aXMLHttpRequest.status == 200 ||
                aXMLHttpRequest.status == 304)) {

            var result = aXMLHttpRequest.responseText;

            if (result.trim().toLowerCase() == "true") {

                alert("Password Changed!");

                window.location = "/";

            } else {

                alert("Password Change Failed!");

            }

        }
    }

</script>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<div id="default" style="width: 100%; height: 400px; text-align: center; vertical-align: top;">

  <div class="button" onclick="window.location = '<%= new_user_path %>'" tag=0>
    <table style="text-align: left;">
      <tr>
        <td rowspan="2">
          <img src="<%= @icoFolder %>" height="60"/>
        </td>
        <td style="height: 30px;">
          Add User
        </td>
      </tr>
      <tr>
        <td style="font-size: 11px; font-style: italic;">
          Add new system user at facility.
        </td>
      </tr>
    </table>
  </div>

  <div class="button" onclick="window.location = '/search_user'" tag=2>
    <table style="text-align: left;">
      <tr>
        <td rowspan="2">
          <img src="<%= @icoFolder %>" height="60"/>
        </td>
        <td style="height: 30px;">
          Edit User
        </td>
      </tr>
      <tr>
        <td style="font-size: 11px; font-style: italic;">
          Edit user record at facility.
        </td>
      </tr>
    </table>
  </div>

  <div class="button" onclick="window.location = '/block'" tag=5>
    <table style="text-align: left;">
      <tr>
        <td rowspan="2">
          <img src="<%= @icoFolder %>" height="60"/>
        </td>
        <td style="height: 30px;">
          Block User
        </td>
      </tr>
      <tr>
        <td style="font-size: 11px; font-style: italic;">
          Revoke user access rights at facility.
        </td>
      </tr>
    </table>
  </div>

  <div class="button" onclick="window.location = '/unblock'" tag=5>
    <table style="text-align: left;">
      <tr>
        <td rowspan="2">
          <img src="<%= @icoFolder %>" height="60"/>
        </td>
        <td style="height: 30px;">
          Unblock User
        </td>
      </tr>
      <tr>
        <td style="font-size: 11px; font-style: italic;">
          Give back access rights to blocked user at facility.
        </td>
      </tr>
    </table>
  </div>

  <div class="button" onclick="window.location = '/view_users'" tag=1>
    <table style="text-align: left;">
      <tr>
        <td rowspan="2">
          <img src="<%= @icoFolder %>" height="60"/>
        </td>
        <td style="height: 30px;">
          View Users
        </td>
      </tr>
      <tr>
        <td style="font-size: 11px; font-style: italic;">
          View all users, their roles and access rights at facility.
        </td>
      </tr>
    </table>
  </div>

</div>

app/views/users/new.html.erb
<%= render 'form' %>