config/routes.rb
Rails.application.routes.draw do

  root 'hq#index'

  get '/search_by_barcode/:id' => "hq#search_by_barcode"

  post '/push_merge' => "hq#push_merge"

  get '/query_to_print' => "hq#query_to_print"

  get '/birth_certificate/:id' => "hq#birth_certificate"

  post 'hq/do_print_these'

  post 'users/update_password'

  get 'users/change_password'

  get 'users/my_account'

  get '/search_by_case/:id' => "hq#search_by_case"

  get '/do_reopen_case/:id' => "hq#do_reopen_case"

  get '/do_close_case/:id' => "hq#do_close_case"

  get '/do_void_case/:id' => "hq#do_void_case"

  get 'hq/re_open_case'

  get 'hq/close_cases'

  get 'hq/void_cases'

  get 'hq/view_cases'
  
  get 'view_cases' => 'hq#view_cases'

  get 'hq/view_closed_cases'

  get 'hq/view_requests'

  get 'hq/manage_duplicates'

  get 'hq/reports'

  get 'hq/print_certificates'

  get 'hq/list_voided_cases'

  get 'hq/manage_sites'

  get 'hq/index'
  
  get 'hq/validate_records'
  
  get 'hq/compare_demographics'

  get "/query_voided" => "children#query_voided"

  get "/query_requests" => "children#query_requests"

  get "/query_closed" => "children#query_closed"

  get "/query" => "children#query"

  get "/view" => "children#view"

  get "/search" => "children#search"

  get "/logout" => "logins#logout"

  get "/login" => "logins#login"

  get "/search_by_fullname/:id" => "children#search_by_fullname"

  get "/search_by_fullname" => "children#search_by_fullname"

  get "/set_context/:id" => "logins#set_context"

  get "/view_users" => "users#view"

  get "/query_users" => "users#query"

  get "/search_user" => "users#search"

  get "/search_by_username/:id" => "users#search_by_username"

  get "/search_by_username" => "users#search_by_username"

  get "/username_availability" => "users#username_availability"

  get "/block_user/:id" => "users#block_user"

  get "/unblock_user/:id" => "users#unblock_user"

  get "/block" => "users#block"

  get "/unblock" => "users#unblock"
  
  get "/case_validation" => "hq#compare_demographics"
  
  get "/validate_records" => "hq#validate_records"
  
  get "/void_child" => "hq#void_child"

  resources :children

  resources :users

  resource :login do
    collection do
      get :logout
    end
  end	

end

app/helpers/hq_helper.rb
module HqHelper
end

app/views/hq/list_voided_cases.html.erb
<div id="table" class="table" style="width: 90%; border-spacing: 0px; margin: auto; margin-top: 40px;">
  <div class="row" style="font-weight: bold;">
    <div class="cell"
         style="border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;">
      #
    </div>
    <div class="cell" style="border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px;">
      Name
    </div>
    <div class="cell"
         style="border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;">
      Mother's Details
    </div>
    <div class="cell"
         style="border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;">
      Father's Details
    </div>
    <div class="cell" style="border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;">
      Status
    </div>
    <div class="cell" style="border-bottom: 1px solid #3465a4; padding: 5px; text-align: center;">
      Operations
    </div>
  </div>
</div>

<!--button id="btnAction" class="blue" style="position: absolute; right: 160px; bottom: 20px;" onclick="window.location = '<%= new_child_path %>'">New
  Child
</button-->

<script>

    var currentPage = 0;
    var people = [];
    var currentPagesize = 8;

    function __$(id) {
        return document.getElementById(id);
    }

    function ajaxTasks(page, pagesize) {

        if (pagesize == undefined)
            pagesize = currentPagesize;

        var url = "/query_voided?page=" + (page + 1) + "&size=" + pagesize;

        var httpRequest = new XMLHttpRequest();
        httpRequest.onreadystatechange = function () {
            handleTasks(httpRequest, page, pagesize);
        };
        try {
            httpRequest.open('GET', url, true);
            httpRequest.send(null);
        } catch (e) {
        }
    }

    function handleTasks(aXMLHttpRequest, page, pagesize) {
        if (!aXMLHttpRequest) return;

        if (aXMLHttpRequest.readyState == 4 && (aXMLHttpRequest.status == 200 ||
                aXMLHttpRequest.status == 304)) {

            var result = JSON.parse(aXMLHttpRequest.responseText);

            people = result;

            loadRows(page, pagesize);

        }
    }

    function loadRows(page, pagesize) {

        if (pagesize == undefined)
            pagesize = currentPagesize;

        var header_cells = [
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center; width: 300px; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; padding: 5px; text-align: center; font-weight: bold;"
        ];

        var header_text = [
            "#",
            "Name",
            "Mother's Details",
            "Father's Details",
            "Status",
            "Operations",
            "&nbsp;"
        ];

        var header_row = document.createElement("div");
        header_row.className = "row";

        if (__$("table")) {

            __$("table").innerHTML = "";

            __$("table").appendChild(header_row);

        }
        for (var c = 0; c < header_cells.length; c++) {

            var cell = document.createElement("div");
            cell.className = "cell";
            cell.setAttribute("style", header_cells[c]);

            cell.innerHTML = header_text[c];

            header_row.appendChild(cell);

        }

        var base = 0;
        var scrollsize = pagesize;

        if (page == 0) {

            base = 0;

            scrollsize = pagesize;

        } else {

            base = (page * pagesize) - page;

            scrollsize = base + pagesize;

        }

        var r = 0;

        for (var i = base; i < scrollsize; i++) {
            var row = document.createElement("div");
            row.className = "row";

            if (__$("table")) {

                __$("table").appendChild(row);

            }

            var cells = [
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;",
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px;",
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px;",
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px;",
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;",
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;",
                "padding: 5px; text-align: center; width: 30px;"
            ]

            for (var c = 0; c < cells.length; c++) {

                var cell = document.createElement("div");
                cell.className = "cell";
                cell.setAttribute("style", cells[c]);
                cell.style.verticalAlign = "middle";

                if (c == cells.length - 1 && i == scrollsize - 1) {

                    cell.style.verticalAlign = "middle";

                    cell.setAttribute("style", cell.getAttribute("style") + " border-bottom: 1px dotted #3465a4;");

                    var arrowdown = document.createElement("div");
                    arrowdown.className = "arrow-down";

                    arrowdown.onclick = function () {

                        currentPage++;

                        ajaxTasks(currentPage);

                    }

                    cell.appendChild(arrowdown);

                } else if (c == cells.length - 1 && i == base) {

                    cell.style.verticalAlign = "middle";

                    var arrowup = document.createElement("div");
                    arrowup.className = "arrow-up";

                    arrowup.onclick = function () {

                        if (currentPage - 1 >= 0)
                            currentPage--;

                        ajaxTasks(currentPage);

                    }

                    cell.appendChild(arrowup);

                } else {

                    if (c == 1) {

                        if (r < people.length) {

                            cell.innerHTML = people[r]["Child"]["First Name"] + " " + people[r]["Child"]["Other Name"] + " " +
                                    people[r]["Child"]["Family Name"];

                        } else {

                            cell.innerHTML = (c == 0 ? (i + 1) : "&nbsp;");

                        }

                    } else if (c == 2) {

                        if (r < people.length) {

                            cell.innerHTML = people[r]["Mother"]["First Name"] + " " + people[r]["Mother"]["Other Name"] + " " +
                                    people[r]["Mother"]["Family Name"];

                        } else {

                            cell.innerHTML = (c == 0 ? (i + 1) : "&nbsp;");

                        }

                    } else if (c == 3) {

                        if (r < people.length) {

                            cell.innerHTML = people[r]["Father"]["First Name"] + " " + people[r]["Father"]["Other Name"] + " " +
                                    people[r]["Father"]["Family Name"];

                        } else {

                            cell.innerHTML = (c == 0 ? (i + 1) : "&nbsp;");

                        }

                    } else if (c == 4) {

                        cell.innerHTML = "";

                        if (r < people.length) {

                            if (people[r]["status"].toUpperCase().trim() == "HQ OPEN" && people[r]["remote_status"].toUpperCase().trim() == "ACTIVE") {

                                var imgView = document.createElement("img");
                                imgView.height = 50;
                                imgView.setAttribute("src", active);

                                cell.appendChild(imgView);

                                root = "un";

                            } else {

                                var imgView = document.createElement("img");
                                imgView.height = 50;
                                imgView.setAttribute("src", blocked);

                                cell.appendChild(imgView);

                                root = "un";

                            }

                        } else {

                            cell.innerHTML = (c == 0 ? (i + 1) : "&nbsp;");

                        }

                    } else if (c == 5) {

                        if (r < people.length) {

                            var btnShow = document.createElement("a");
                            btnShow.setAttribute("href", "/children/" + people[r]["id"]);

                            cell.appendChild(btnShow);

                            var imgView = document.createElement("img");
                            imgView.height = 60;
                            imgView.setAttribute("src", icoView);

                            btnShow.appendChild(imgView);

                            if(people[r]["status"].toUpperCase().trim() == "HQ OPEN" && people[r]["remote_status"].toUpperCase().trim() == "ACTIVE") {

                                var btnEdit = document.createElement("a");
                                btnEdit.setAttribute("href", "/children/" + people[r]["id"] + "/edit");
                                btnEdit.style.marginLeft = "30px";
                                btnEdit.style.marginRight = "30px";

                                cell.appendChild(btnEdit);

                                var imgEdit = document.createElement("img");
                                imgEdit.height = 60;
                                imgEdit.setAttribute("src", icoEdit);

                                btnEdit.appendChild(imgEdit);

                                var btnDelete = document.createElement("a");
                                btnDelete.setAttribute("data-method", "delete");
                                btnDelete.setAttribute("ref", "nofollow");
                                btnDelete.setAttribute("data-confirm", "Are you sure?");
                                btnDelete.setAttribute("href", "/children/" + people[r]["id"]);

                                cell.appendChild(btnDelete);

                                var imgDelete = document.createElement("img");
                                imgDelete.height = 60;
                                imgDelete.setAttribute("src", icoDelete);

                                btnDelete.appendChild(imgDelete);

                            }

                        } else {

                            cell.innerHTML = "<div style='height: 60px;'>&nbsp;</div>";

                        }

                    } else {

                        cell.style.verticalAlign = "middle";

                        cell.innerHTML = (c == 0 ? (i + 1) : "&nbsp;");

                    }

                }

                row.appendChild(cell);

            }

            r++;
        }
    }

    currentPage = 0;

    ajaxTasks(currentPage);

</script>

app/views/hq/manage_sites.html.erb
<h1>Hq#manage_sites</h1>
<p>Find me in app/views/hq/manage_sites.html.erb</p>

app/views/hq/reports.html.erb
<h1>Hq#reports</h1>
<p>Find me in app/views/hq/reports.html.erb</p>

app/views/hq/view_cases.html.erb
<div id="table" class="table" style="width: 90%; border-spacing: 0px; margin: auto; margin-top: 40px;">
  <div class="row" style="font-weight: bold;">
    <div class="cell"
         style="border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;">
      #
    </div>
    <div class="cell" style="border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px;">
      Name
    </div>
    <div class="cell"
         style="border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;">
      Mother's Details
    </div>
    <div class="cell"
         style="border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;">
      Father's Details
    </div>
    <div class="cell" style="border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;">
      Status
    </div>
    <div class="cell" style="border-bottom: 1px solid #3465a4; padding: 5px; text-align: center;">
      Operations
    </div>
  </div>
</div>

<!--button id="btnAction" class="blue" style="position: absolute; right: 160px; bottom: 20px;" onclick="window.location = '<%= new_child_path %>'">New
  Child
</button-->

<script>

    var currentPage = 0;
    var people = [];
    var currentPagesize = 8;

    function __$(id) {
        return document.getElementById(id);
    }

    function ajaxTasks(page, pagesize) {

        if (pagesize == undefined)
            pagesize = currentPagesize;

        var url = "/query?page=" + (page + 1) + "&size=" + pagesize;

        var httpRequest = new XMLHttpRequest();
        httpRequest.onreadystatechange = function () {
            handleTasks(httpRequest, page, pagesize);
        };
        try {
            httpRequest.open('GET', url, true);
            httpRequest.send(null);
        } catch (e) {
        }
    }

    function handleTasks(aXMLHttpRequest, page, pagesize) {
        if (!aXMLHttpRequest) return;

        if (aXMLHttpRequest.readyState == 4 && (aXMLHttpRequest.status == 200 ||
                aXMLHttpRequest.status == 304)) {

            var result = JSON.parse(aXMLHttpRequest.responseText);

            people = result;

            loadRows(page, pagesize);

        }
    }

    function loadRows(page, pagesize) {

        if (pagesize == undefined)
            pagesize = currentPagesize;

        var header_cells = [
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 2px; font-weight: bold; text-align: center;",
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center; width: 300px; font-weight: bold;",
            "border-bottom: 1px solid #3465a4; padding: 5px; text-align: center; font-weight: bold;"
        ];

        var header_text = [
            "#",
            "Name",
            "Birth Entry Number",
            "Mother's Details",
            "Father's Details",
            "Status",
            "Operations",
            "&nbsp;"
        ];

        var header_row = document.createElement("div");
        header_row.className = "row";

        if (__$("table")) {

            __$("table").innerHTML = "";

            __$("table").appendChild(header_row);

        }
        for (var c = 0; c < header_cells.length; c++) {

            var cell = document.createElement("div");
            cell.className = "cell";
            cell.setAttribute("style", header_cells[c]);

            cell.innerHTML = header_text[c];

            header_row.appendChild(cell);

        }

        var base = 0;
        var scrollsize = pagesize;

        if (page == 0) {

            base = 0;

            scrollsize = pagesize;

        } else {

            base = (page * pagesize) - page;

            scrollsize = base + pagesize;

        }

        var r = 0;

        for (var i = base; i < scrollsize; i++) {
            var row = document.createElement("div");
            row.className = "row";

            if (__$("table")) {

                __$("table").appendChild(row);

            }

            var cells = [
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;",
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px;",
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px;width: 160px;text-align: center;",
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px;",
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px;",
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;",
                "border-bottom: 1px dotted #3465a4; border-right: 1px dotted #3465a4; padding: 5px; text-align: center;",
                "padding: 5px; text-align: center; width: 30px;"
            ]

            for (var c = 0; c < cells.length; c++) {

                var cell = document.createElement("div");
                cell.className = "cell";
                cell.setAttribute("style", cells[c]);
                cell.style.verticalAlign = "middle";

                if (c == cells.length - 1 && i == scrollsize - 1) {

                    cell.style.verticalAlign = "middle";

                    cell.setAttribute("style", cell.getAttribute("style") + " border-bottom: 1px dotted #3465a4;");

                    var arrowdown = document.createElement("div");
                    arrowdown.className = "arrow-down";

                    arrowdown.onclick = function () {

                        currentPage++;

                        ajaxTasks(currentPage);

                    }

                    cell.appendChild(arrowdown);

                } else if (c == cells.length - 1 && i == base) {

                    cell.style.verticalAlign = "middle";

                    var arrowup = document.createElement("div");
                    arrowup.className = "arrow-up";

                    arrowup.onclick = function () {

                        if (currentPage - 1 >= 0)
                            currentPage--;

                        ajaxTasks(currentPage);

                    }

                    cell.appendChild(arrowup);

                } else {

                    if (c == 1) {

                        if (r < people.length) {

                            cell.innerHTML = people[r]["Child"]["First Name"] + " " + people[r]["Child"]["Other Name"] + " " +
                                    people[r]["Child"]["Family Name"];

                        } else {

                            cell.innerHTML = (c == 0 ? (i + 1) : "&nbsp;");

                        }

                    } else if (c == 2) {

                        if (r < people.length) {

                            cell.innerHTML = people[r]["district_id_number"] ;

                        } else {

                            cell.innerHTML = (c == 0 ? (i + 1) : "&nbsp;");

                        }

                    } else if (c == 3) {

                        if (r < people.length) {

                            cell.innerHTML = people[r]["Mother"]["First Name"] + " " + people[r]["Mother"]["Other Name"] + " " +
                                    people[r]["Mother"]["Family Name"];

                        } else {

                            cell.innerHTML = (c == 0 ? (i + 1) : "&nbsp;");

                        } 
                    
                    
                    } else if (c == 4) {

                        if (r < people.length) {

                            cell.innerHTML = people[r]["Father"]["First Name"] + " " + people[r]["Father"]["Other Name"] + " " +
                                    people[r]["Father"]["Family Name"];

                        } else {

                            cell.innerHTML = (c == 0 ? (i + 1) : "&nbsp;");

                        }

                    } else if (c == 5) {

                        cell.innerHTML = "";

                        if (r < people.length) {

                            if (people[r]["status"].toUpperCase().trim() == "HQ OPEN" && people[r]["remote_status"].toUpperCase().trim() == "ACTIVE") {

                                var imgView = document.createElement("img");
                                imgView.height = 50;
                                imgView.setAttribute("src", active);
                                imgView.setAttribute("title", "Active Record");
                                cell.appendChild(imgView);

                                root = "un";

                            } else if (people[r]["status"].toUpperCase().trim() == "PRINTED" && people[r]["remote_status"].toUpperCase().trim() == "CLOSED") {

                                var imgView = document.createElement("img");
                                imgView.height = 50;
                                imgView.setAttribute("src", printed);
                                imgView.setAttribute("title", "Printed Record");
                                cell.appendChild(imgView);

                                root = "un";

                            } else {

                                var imgView = document.createElement("img");
                                imgView.height = 50;
                                imgView.setAttribute("src", blocked);
                                imgView.setAttribute("title", "Readonly Record");
                                cell.appendChild(imgView);

                                root = "un";

                            }

                        } else {

                            cell.innerHTML = (c == 0 ? (i + 1) : "&nbsp;");

                        }

                    } else if (c == 6) {

                        if (r < people.length) {

                            var btnShow = document.createElement("a");
                            btnShow.setAttribute("href", "/children/" + people[r]["id"]);

                            cell.appendChild(btnShow);

                            var imgView = document.createElement("img");
                            imgView.height = 60;
                            imgView.setAttribute("src", icoView);
                            imgView.setAttribute("title", "View Record");
                            btnShow.appendChild(imgView);
                            
                        } else {

                            cell.innerHTML = "<div style='height: 60px;'>&nbsp;</div>";

                        }

                    } else {

                        cell.style.verticalAlign = "middle";

                        cell.innerHTML = (c == 0 ? (i + 1) : "&nbsp;");

                    }

                }

                row.appendChild(cell);

            }

            r++;
        }
    }
    
    function confirmDelete(pos){
   
      window.location = "/void_child?id=" + people[pos]["id"];
    
    }

    currentPage = 0;

    ajaxTasks(currentPage);

</script>